export enum AiTextMode {
  AUTO = 'AUTO',
  CORREGIR = 'CORREGIR',
  REFORMULAR = 'REFORMULAR',
  FORMAL = 'FORMAL',
  INFORMAL = 'INFORMAL',
  RESUMIR = 'RESUMIR',
  RESPONDER = 'RESPONDER',
  EXPLICAR = 'EXPLICAR',
  GENERAR_RESPUESTA = 'GENERAR_RESPUESTA',
  GENERAR_EMAIL = 'GENERAR_EMAIL',
  COMPLETAR_TEXTO = 'COMPLETAR_TEXTO',
}
